default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || (if Sidekiq.server? then Sidekiq.default_configuration[:concurrency] else ENV['MAX_THREADS'] end) || 5 %>
  timeout: 5000
  connect_timeout: 15
  encoding: unicode
  sslmode: <%= ENV['DB_SSLMODE'] || "prefer" %>
  application_name: ''

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  replica:
    <<: *default
    url: <%= ENV['REPLICA_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    replica: true

test:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  replica:
    <<: *default
    url: <%= ENV['REPLICA_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    replica: true

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  replica:
    <<: *default
    url: <%= ENV['REPLICA_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    replica: true
    database_tasks: <%= ENV['REPLICA_DB_TASKS'] || 'true' %>
