defaults: &defaults
  site_title: Mastowork
  site_short_description: 'Public Mastodon instance currently in development'
  site_description: >
    Mastowork is a public Mastodon instance currently in development.
    At this stage, signup is by approval only to help us ensure quality and stability.
    No reason is required when requesting access. We encourage users to use c.im
    while we finalize the setup. Thank you for your patience and support!
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'approval'     # signup requires approval
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: true
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  theme: 'system'
  trends: true
  trends_as_landing_page: true
  trendable_by_default: false
  reserved_usernames:
    - abuse
    - account
    - accounts
    - admin
    - administration
    - administrator
    - admins
    - help
    - helpdesk
    - instance
    - mod
    - moderator
    - moderators
    - mods
    - owner
    - root
    - security
    - server
    - staff
    - support
    - webmaster
    - stetup        # reserved admin username
  disallowed_hashtags: []
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false
  allow_referer_origin: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
